/* Generated By:JavaCC: Do not edit this line. SqlStatementInfoExtractorConstants.java */


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SqlStatementInfoExtractorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Select = 1;
  /** RegularExpression Id. */
  int Insert = 2;
  /** RegularExpression Id. */
  int Delete = 3;
  /** RegularExpression Id. */
  int Update = 4;
  /** RegularExpression Id. */
  int Merge = 5;
  /** RegularExpression Id. */
  int From = 6;
  /** RegularExpression Id. */
  int Into = 7;
  /** RegularExpression Id. */
  int Join = 8;
  /** RegularExpression Id. */
  int Comma = 9;
  /** RegularExpression Id. */
  int OpenParen = 10;
  /** RegularExpression Id. */
  int CloseParen = 11;
  /** RegularExpression Id. */
  int OpenComment = 12;
  /** RegularExpression Id. */
  int CloseComment = 13;
  /** RegularExpression Id. */
  int Identifier = 14;
  /** RegularExpression Id. */
  int UnicodeChar = 15;
  /** RegularExpression Id. */
  int Whitespace = 16;
  /** RegularExpression Id. */
  int Other = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"SELECT\"",
    "\"INSERT\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"MERGE\"",
    "\"FROM\"",
    "\"INTO\"",
    "\"JOIN\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"/*\"",
    "\"*/\"",
    "<Identifier>",
    "<UnicodeChar>",
    "<Whitespace>",
    "<Other>",
  };

}
